import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "./(components)/app-sidebar";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider  from "./provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen m-0 p-0`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="grow overflow-hidden"  >
            <SidebarTrigger />
            <Provider>
              {children}
            </Provider>
          </main>
        </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
